# api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

      default-filters:
        - RemoveRequestHeader=Cookie
        - RemoveRequestHeader=Set-Cookie
        # Add JWT authentication filter here if needed

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
